// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependencies

import (
	"app/xonvera-core/internal/adapters/handler/http"
	"app/xonvera-core/internal/adapters/middleware"
	"app/xonvera-core/internal/adapters/repositories/redis"
	"app/xonvera-core/internal/adapters/repositories/sql"
	"app/xonvera-core/internal/core/services"
	"app/xonvera-core/internal/infrastructure/config"
	"app/xonvera-core/internal/infrastructure/database"
	"app/xonvera-core/internal/infrastructure/redis"
	"app/xonvera-core/internal/infrastructure/server"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	redis2 "github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"time"
)

// Injectors from wire.go:

// InitializeApplication creates a new Application with all dependencies wired
func InitializeApplication() (*Application, error) {
	configConfig := config.LoadConfig()
	databaseConfig := ProvideDBConfig(configConfig)
	db, err := database.NewConnection(databaseConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := ProvideRedisConfig(configConfig)
	client := redis.NewRedisClient(redisConfig)
	app := server.NewFiberApp(configConfig, client, db)
	userRepository := repositoriesSql.NewUserRepository(db)
	tokenRepository := repositoriesRedis.NewTokenRepository(client)
	tokenConfig := ProvideTokenConfig(configConfig)
	tokenService := services.NewTokenService(tokenConfig)
	authService := services.NewAuthService(userRepository, tokenRepository, tokenService, tokenConfig)
	duration := ProvideRequestTimeout(configConfig)
	authHandler := http.NewAuthHandler(authService, duration)
	packageRepository := repositoriesSql.NewPackageRepository(db)
	packageService := services.NewPackageService(packageRepository)
	packageHandler := http.NewPackageHandler(packageService)
	invoiceRepository := repositoriesSql.NewInvoiceRepository(db)
	invoiceService := services.NewInvoiceService(invoiceRepository)
	invoiceHandler := http.NewInvoiceHandler(invoiceService, duration)
	authMiddleware := middleware.NewAuthMiddleware(authService, duration)
	application := &Application{
		Config:         configConfig,
		DB:             db,
		Redis:          client,
		FiberApp:       app,
		AuthHandler:    authHandler,
		PackageHandler: packageHandler,
		InvoiceHandler: invoiceHandler,
		AuthMiddleware: authMiddleware,
	}
	return application, nil
}

// wire.go:

// ProviderSet is the set of all providers
var ProviderSet = wire.NewSet(config.LoadConfig, ProvideDBConfig,
	ProvideTokenConfig,
	ProvideRedisConfig,
	ProvideRequestTimeout, database.NewConnection, redis.NewRedisClient, server.NewFiberApp, repositoriesSql.NewUserRepository, repositoriesSql.NewPackageRepository, repositoriesSql.NewInvoiceRepository, repositoriesRedis.NewTokenRepository, services.NewTokenService, services.NewAuthService, services.NewPackageService, services.NewInvoiceService, http.NewAuthHandler, http.NewPackageHandler, http.NewInvoiceHandler, middleware.NewAuthMiddleware,
)

// ProvideDBConfig extracts DatabaseConfig from Config
func ProvideDBConfig(cfg *config.Config) *config.DatabaseConfig {
	return &cfg.Database
}

// ProvideTokenConfig extracts TokenConfig from Config
func ProvideTokenConfig(cfg *config.Config) *config.TokenConfig {
	return &cfg.Token
}

// ProvideRedisConfig extracts RedisConfig from Config
func ProvideRedisConfig(cfg *config.Config) *config.RedisConfig {
	return &cfg.Redis
}

// ProvideRequestTimeout extracts request timeout from Config
func ProvideRequestTimeout(cfg *config.Config) time.Duration {
	return cfg.App.RequestTimeout
}

// Application holds all the dependencies
type Application struct {
	Config         *config.Config
	DB             *gorm.DB
	Redis          *redis2.Client
	FiberApp       *fiber.App
	AuthHandler    *http.AuthHandler
	PackageHandler *http.PackageHandler
	InvoiceHandler *http.InvoiceHandler
	AuthMiddleware *middleware.AuthMiddleware
}
